### ISSUE TITLE
Error when running `example.py`

### ISSUE THREAD

**Issue by AlpinDale** [miku448/aphrodite-guidance#1]
Great work! I tried running it earlier today and ran into this traceback:

```
Traceback (most recent call last):
  File "/home/pyg1/aphrodite-engine/conda/envs/aphrodite-runtime/lib/python3.10/site-packages/guidance/llms/_openai.py", line 665, in __call__
    out = await self.llm.caller(**call_args)
  File "/home/pyg1/aphrodite-engine/conda/envs/aphrodite-runtime/lib/python3.10/site-packages/guidance/llms/_openai.py", line 348, in _library_call
    prev_base = openai.api_base
AttributeError: module 'openai' has no attribute 'api_base'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pyg1/aphrodite-engine/conda/envs/aphrodite-runtime/lib/python3.10/site-packages/guidance/_program_executor.py", line 109, in run
    await self.visit(self.parse_tree, VariableStack([self.program._variables], self))
  File "/home/pyg1/aphrodite-engine/conda/envs/aphrodite-runtime/lib/python3.10/site-packages/guidance/_program_executor.py", line 559, in visit
    visited_children.append(await self.visit(child, variable_stack, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "/home/pyg1/aphrodite-engine/conda/envs/aphrodite-runtime/lib/python3.10/site-packages/guidance/_program_executor.py", line 266, in visit
    visited_children = [await self.visit(child, variable_stack, next_node, next_next_node, prev_node, node, parent_node) for child in node]
  File "/home/pyg1/aphrodite-engine/conda/envs/aphrodite-runtime/lib/python3.10/site-packages/guidance/_program_executor.py", line 266, in <listcomp>
    visited_children = [await self.visit(child, variable_stack, next_node, next_next_node, prev_node, node, parent_node) for child in node]
  File "/home/pyg1/aphrodite-engine/conda/envs/aphrodite-runtime/lib/python3.10/site-packages/guidance/_program_executor.py", line 379, in visit
    command_output = await command_function(*positional_args, **named_args)
  File "/home/pyg1/aphrodite-engine/conda/envs/aphrodite-runtime/lib/python3.10/site-packages/guidance/library/_gen.py", line 140, in gen
    gen_obj = await parser.llm_session(
  File "/home/pyg1/aphrodite-engine/conda/envs/aphrodite-runtime/lib/python3.10/site-packages/guidance/llms/_openai.py", line 667, in __call__
    except openai.error.RateLimitError:
AttributeError: module 'openai' has no attribute 'error'

Error in program:  module 'openai' has no attribute 'error'
```

Then it fails to properly apply Guidance:

```
+------------------------------------------------------------------------------+
|Example 1                                                                     |
+------------------------------------------------------------------------------+
Prompt:
+---------------------------------------------------------------------------------------------------+
|I will show you an email and a response, and you will tell me if it's offensive.                   |
|Email: {{email}}.                                                                                  |
|Response: I also don't{{gen "response" stop="."}}                                                  |
|Is the response above offensive in any way? Please answer with a single word, either "Yes" or "No".|
|Answer:{{#select "answer" logprobs='logprobs'}} Yes{{or}} No{{/select}}                            |
+---------------------------------------------------------------------------------------------------+
Completion:
+---------------------------------------------------------------------------------------------------+
|I will show you an email and a response, and you will tell me if it's offensive.                   |
|Email: I hate tacos.                                                                               |
|Response: I also don't                                                                             |
|Is the response above offensive in any way? Please answer with a single word, either "Yes" or "No".|
|Answer:                                                                                            |
+---------------------------------------------------------------------------------------------------+
```

**Comment by miku448** [comment]
I think this might be a problem with guidance using an old openai package and not enforcing it.

this might solve it:
```bash
pip install openai==0.27.8
```

**Comment by AlpinDale** [comment]
That indeed fixed it, thanks.
